# Generated by Django 3.2.6 on 2021-08-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название публикации')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='post_images', verbose_name='Фото публикации')),
                ('text', models.TextField(verbose_name='Текст/содержание публикации')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания публикации')),
            ],
        ),
    ]
